# Generated by Django 5.2 on 2025-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company Information'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='content',
            new_name='history',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='department',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Staff', max_length=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
