# Generated by Django 5.2 on 2025-06-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_article_promocode_delete_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
